### ISSUE TITLE
Nothing found when anything is searched

### ISSUE THREAD

**Issue by nothing223** [riteable/soulsearch#3]
Whenever I search anything I get the message "Hmm... Couldn't find anything". It was working fine 2 or 3 weeks ago but recently stopped. I have tried using a vpn and turning off browser extensions however, none worked. A fix would be greatly appreciated.

**Comment by riteable** [comment]
Are you using the demo app? If so, it should be working now.

**Comment by nothing223** [comment]
Working fine now. Thanks.

**Comment by nothing223** [comment]
Stopped working again. I'm getting the same message.

**Comment by somedude305** [comment]
Same problem this just doesn't work at all for me not sure why. No results on every search

**Comment by somedude305** [comment]
It's working for me today 👍

**Comment by nothing223** [comment]
Stopped working again. No results when anything is searched.

**Comment by riteable** [comment]
I have discontinued the demo. The app doesn't scale for multiple users/visitors due to the underlying Soulseek protocol, which is meant to be used by a single login.

**Comment by ghost** [comment]
Will the site ever return? Theres some stuff i really want to download but cant find anywere else :(

**Comment by riteable** [comment]
Sorry, but I don't think I'll be hosting the site anytime soon. You could just install the official Soulseek client on a desktop machine and find whatever you need.

**Comment by ghost** [comment]
I would but im a bit young and live with my parents and dont have access to the router to port forward which is needed to use Soulseek.
